export enum COLUMN_IDS {
  requestId = 'leadRequest/requestId',
  loanId = 'leadResponse/loanId',
  leadProvider = 'leadRequest/leadProviderId',
  leadCampaign = 'leadRequest/campaignId',
  customerId = 'leadResponse/customerId',
  leadPrice = 'leadResponse/leadPrice',
  affiliate = 'leadRequest/affiliateId',
  requestDate = 'processingMetadata/processingDateTimeUtc',
  requestedAmount = 'leadRequest/requestedAmount',
  stackName = 'output/stack',
  promoCode = 'leadRequest/customFields/promoCode',
  store = 'output/store',
  ssn = 'leadRequest/ssn',
  email = 'leadRequest/email',
  state = 'leadRequest/state',
  decision = 'output/decision',
  denialReason = 'output/denialReason',
  apiVersion = 'processingMetadata/apiVersion',
  totalTime = 'processingMetadata/processingTime',
  cachedConnector = 'processingMetadata/cachedConnector',
  details = 'details'
}
